services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    environment:
      - HUGGING_FACE_HUB_TOKEN=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
    volumes:
      - ./code:/code
    user: "1000:1000"